CREATE TABLE Cities(
	CityID INT IDENTITY PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL,
);

CREATE TABLE Customers(
	CustomerID INT IDENTITY PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL,
	Birthday DATE,
	CityID INT REFERENCES Cities(CityID),
);

CREATE TABLE Orders(
	OrderID INT IDENTITY PRIMARY KEY,
	CustomerID INT NOT NULL REFERENCES Customers(CustomerID),
);

CREATE TABLE ItemTypes(
	ItemTypeID INT IDENTITY PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL,
);

CREATE TABLE Items(
	ItemID INT IDENTITY PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL,
	ItemTypeID INT NOT NULL REFERENCES ItemTypes(ItemTypeID),
);

CREATE TABLE OrderItems(
	OrderID INT NOT NULL REFERENCES Orders(OrderID),
	ItemID INT NOT NULL REFERENCES Items(ItemID),
	CONSTRAINT PK_OrderID_ItemID
	PRIMARY KEY (OrderID, ItemID)
);