-- ADD DEFAULT CONSTRAINT FOR LastLoginTime TO BE CURRENT TIME ON TABLE Users IN DATABASE Users, task 11

USE Users

ALTER TABLE Users
ADD CONSTRAINT DF_Users_LLTimeEqualsCurrentTime
DEFAULT GETDATE() FOR LastLoginTime