-- ADD CHECK CONSTRAINT TO ENSURE THAT VALUES IN THE [PASSWORD] FIELD ARE AT LEAST 5 SYMBOLS LONG, IN Users DATABASE, task 10

USE Users

ALTER TABLE Users
ADD CONSTRAINT CK_Users_FiveSymbolsLongPassword
CHECK(LEN(Password) >= 5)