-- REMOVE Username FROM THE PK CONSTRAINT AND ADD UNIQE USERNAME CONSTRAINT TO THE Username TO Users TABLE IN Users DATABASE, task 12

USE Users

ALTER TABLE Users
DROP CONSTRAINT [PK_Users_CompositeIdUsername]

ALTER TABLE Users
ADD CONSTRAINT PK_Users_Id
PRIMARY KEY(Id)

ALTER TABLE Users
ADD CONSTRAINT UQ_Users_Username
UNIQUE(Username),
CHECK(LEN(Username) >= 3)